Make spm matlab calls more robust using try and batch mode; update FSL feat to latest TCL; amend flame_runner to be robust

diff --git a/inst/bin/flame_runner b/inst/bin/flame_runner
--- a/inst/bin/flame_runner
+++ b/inst/bin/flame_runner
@@ -6,26 +6,97 @@ fi
 
 flame_list="$1"
 njobs="$2"
-cmd_parallel=$( command -v parallel )
-[ $? -eq 0 ] && has_parallel=1 || has_parallel=0
 
-cmd_xargs=$( command -v xargs )
-[ $? -eq 0 ] && has_xargs=1 || has_xargs=0
+if [ ! -f "$flame_list" ]; then
+    echo "flame_runner: command list not found: $flame_list"
+    exit 1
+fi
 
-if [ $has_parallel -eq 1 ]; then
-    #echo "Using parallel"
-    $cmd_parallel -j $njobs < $flame_list
-elif [ $has_xargs -eq 1 ]; then
-    #echo "Using xargs"
-    cat $flame_list | xargs -n 1 -P $njobs -I '{}' sh -c '{}'
+if ! [[ "$njobs" =~ ^[0-9]+$ ]]; then
+    echo "flame_runner: max jobs must be a positive integer (got: $njobs)"
+    exit 1
+fi
+
+detect_alloc() {
+    local v
+    for v in "${SLURM_CPUS_PER_TASK:-}" "${SLURM_NTASKS:-}" "${SLURM_CPUS_ON_NODE:-}" "${PBS_NP:-}" "${NCPUS:-}" "${PBS_NUM_PPN:-}"; do
+        if [[ "$v" =~ ^[0-9]+$ ]] && [ "$v" -gt 0 ]; then
+            echo "$v"
+            return 0
+        fi
+    done
+    return 1
+}
+
+alloc="$(detect_alloc)"
+if [ -n "$alloc" ] && [ "$alloc" -gt 0 ] && [ "$njobs" -gt "$alloc" ]; then
+    njobs="$alloc"
+fi
+
+nslices=$(grep -cve '^[[:space:]]*$' "$flame_list")
+if [ "$nslices" -le 0 ]; then
+    echo "flame_runner: no commands found in $flame_list"
+    exit 1
+fi
+if [ "$njobs" -gt "$nslices" ]; then
+    njobs="$nslices"
+fi
+if [ "$njobs" -le 0 ]; then
+    njobs=1
+fi
+
+cmd_parallel=$(command -v parallel)
+cmd_xargs=$(command -v xargs)
+
+has_parallel=0
+has_xargs=0
+xargs_supports_d=0
+
+[ -n "$cmd_parallel" ] && has_parallel=1
+[ -n "$cmd_xargs" ] && has_xargs=1
+
+if [ "$has_xargs" -eq 1 ]; then
+    if "$cmd_xargs" --help 2>&1 | grep -q -- '-d'; then
+        xargs_supports_d=1
+    fi
+fi
+
+if [ "$has_parallel" -eq 1 ]; then
+    "$cmd_parallel" --jobs "$njobs" --halt now,fail=1 < "$flame_list"
+    exit $?
+elif [ "$has_xargs" -eq 1 ] && [ "$xargs_supports_d" -eq 1 ]; then
+    "$cmd_xargs" -d '\n' -n 1 -P "$njobs" -I '{}' sh -c '{}' < "$flame_list"
+    exit $?
 else
-    #echo "Using while loop"
-    while read -r line;
-    do
-	while [[ $(jobs -r -p | wc -l) -ge $njobs ]]; do
-	    sleep 20 #wait for 20 seconds before repolling
-	done
-	sh -c "$line" & #run line
-    done < $flame_list
-    wait
+    running=0
+    fail=0
+
+    wait_one() {
+        local status
+        wait -n
+        status=$?
+        running=$((running - 1))
+        if [ "$status" -ne 0 ]; then
+            fail=1
+        fi
+    }
+
+    while IFS= read -r line; do
+        if [ -z "${line//[[:space:]]/}" ]; then
+            continue
+        fi
+        while [ "$running" -ge "$njobs" ]; do
+            wait_one
+        done
+        sh -c "$line" &
+        running=$((running + 1))
+    done < "$flame_list"
+
+    while [ "$running" -gt 0 ]; do
+        wait_one
+    done
+
+    if [ "$fail" -ne 0 ]; then
+        exit 1
+    fi
 fi
